- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
Some little issues were causing unnecessarily problems and crashlytics spam.
> Minor fixes

- Atarashii/res/menu/cover_action_menu.xml
- Atarashii/res/menu/record_popup.xml
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
I noticed that not many users were using this so this will be removed.
https://plus.google.com/104507099988539338550/posts/fveWtyDFdUx
> Remove copy function in the popup (IGF)

- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/FirstTimeInit.java
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- Atarashii/src/net/somethingdreadful/MAL/PrefManager.java
- Atarashii/src/net/somethingdreadful/MAL/ProfileActivity.java
- Atarashii/src/net/somethingdreadful/MAL/SearchActivity.java
- Atarashii/src/net/somethingdreadful/MAL/SettingsFragment.java
- Atarashii/src/net/somethingdreadful/MAL/Theme.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/UpdateImageDialogFragment.java
It was a pain to create in each activity and fragment a new PrefManager.
So I made all methods static and let the Theme create it once. We can just use now PrefManager.get... and DONE.
> Make PrefManager static to avoid to create multipe new ones (PrefManager)

- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
The method was kinda long so I improved it. We will use now 2 methods which will reduce the amount of codes.
> Cleanup Save anime to anime relation method

- Atarashii/res/layout-w720dp/activity_detailview_personal.xml
- Atarashii/res/layout/activity_detailview_personal.xml
- Atarashii/res/layout/card_detailview_personal_basic.xml
- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewGeneral.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/DetailViewPagerAdapter.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALApi.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALInterface.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/DatePickerDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/sql/MALSqlHelper.java
This PR will add the start and end read/watching for the manga/anime records ^^
> Add start/end watching/reading

- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
This will change the "none" string into "unknown".
The none string was used for the start/stop dates.
> Change "none" to "Unknown" (DetailView)

- Atarashii/res/values-ar/strings.xml
- Atarashii/res/values-de/strings.xml
- Atarashii/res/values-el/strings.xml
- Atarashii/res/values-es/strings.xml
- Atarashii/res/values-fr/strings.xml
- Atarashii/res/values-nl/strings.xml
- Atarashii/res/values-pl/strings.xml
- Atarashii/res/values-pt-rBR/strings.xml
- Atarashii/res/values-pt-rPT/strings.xml
Update translations for the next RC 1
> Update translations for the RC

- Atarashii/src/net/somethingdreadful/MAL/Card.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewGeneral.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
There was a major bug in Android 4.1.2 that was conflicting our own methods in the custom view.
> Fix Android 4.1.2 bug causing padding problems (Card)

- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/EpisodesPickerDialogFragment.java
- Picasso crash when the application couldn't find the profile anywhere
- numberpicker dialog crash. on some android version it pas null instead 0.
> Fix bugs that were present in the RC

- Atarashii/src/net/somethingdreadful/MAL/tasks/NetworkTask.java
Change crashlytics custom ID keys into Logs to make it simple (NetworkTask)
> Change crashlytics custom ID keys into Logs to make it simple (NetworkTask)

- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
Fix Last online time which was saved wrong in the DB (DatabaseManager)
> Fix Last online time which was saved wrong in the DB (DatabaseManager)

- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/IGFPagerAdapter.java
- Atarashii/src/net/somethingdreadful/MAL/sql/MALSqlHelper.java
- fix database upgrade crash 6 -> 9
- fix IGF nullpointerexception crash
> Fixes beta 2.0

- Atarashii/src/net/somethingdreadful/MAL/tasks/NetworkTask.java
Log Anime & Manga id before peforming actions (NetworkTask)
> Log Anime & Manga id before peforming actions (NetworkTask)

- Atarashii/build.gradle
- Atarashii/src/net/somethingdreadful/MAL/api/response/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Forum.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/ForumMain.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/MangaList.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Profile.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/ProfileAnimeStats.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/ProfileDetails.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/ProfileMangaStats.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/RecordStub.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Statistics.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/User.java
This PR will merge lombok into atarashii which will take over the get & set methods.
> Add lombok project to reduce the amount of codes

- Atarashii/src/net/somethingdreadful/MAL/ForumActivity.java
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/ForumChildDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/forum/ForumsTopics.java
This PR will fix 2 forum bugs, see the commit messages for info.
> Fix forum bugs

- .gitignore
- Atarashii/res/layout-w720dp/activity_detailview_personal.xml
- Atarashii/res/layout/activity_detailview_details.xml
- Atarashii/res/layout/activity_detailview_general.xml
- Atarashii/res/layout/activity_detailview_personal.xml
- Atarashii/res/layout/card_detailview_details_mediainfo.xml
- Atarashii/res/layout/card_detailview_personal_basic.xml
- Atarashii/res/layout/card_detailview_personal_other.xml
- Atarashii/res/layout/card_detailview_personal_rewatch.xml
- Atarashii/res/layout/dialog_message.xml
- Atarashii/res/menu/activity_home.xml
- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewDetails.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewGeneral.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
- Atarashii/src/net/somethingdreadful/MAL/ForumActivity.java
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/MALManager.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/DetailViewPagerAdapter.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/ListDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/MessageDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/NumberPickerDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/sql/MALSqlHelper.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/WriteDetailTask.java
This Pr will bring new personal details like rewatching value and comments.
> Support new personal details for MAL

- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/forum/HtmlUtil.java
- Atarashii/src/net/somethingdreadful/MAL/forum/PostsInterface.java
Another PR for forum fixes.
Note: Youtube comments can't be updated!
> Forum fixes

- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/NetworkTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/UserNetworkTask.java
This PR will fix several bugs related to AniList.
> AniList fixes

- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALApi.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/sql/MALSqlHelper.java
Due the new dirty flag system many personal details were broken and not working.
This PR will fix all of them.
> Fix all the extended details

- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- By moving the function to the getView method in the adapter the response time will be shorter thus faster.
> Enchance IGF peformance by loading faster

- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/IGFPagerAdapter.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/NumberPickerDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/sql/MALSqlHelper.java
This PR will fix some famous crashlytics problems.
> Crashlytics reports fixes

- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewDetails.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Manga.java
The rewatching values weren't working automatically when an user completed the anime/manga for the second time.
> Fix rewatching

- Atarashii/build.gradle
- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/FirstTimeInit.java
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- Atarashii/src/net/somethingdreadful/MAL/ProfileActivity.java
- Atarashii/src/net/somethingdreadful/MAL/SearchActivity.java
- Atarashii/src/net/somethingdreadful/MAL/Theme.java
- Atarashii/src/net/somethingdreadful/MAL/UpdateReceiver.java
- Atarashii/src/net/somethingdreadful/MAL/forum/PostsInterface.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileDetailsAL.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileDetailsMAL.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileFriends.java
This PR will replace toast with Snackbar. This is written in the official material documentation: http://www.google.com/design/spec/components/snackbars-toasts.html
> Snackbar (Material)

- Atarashii/src/net/somethingdreadful/MAL/DetailViewGeneral.java
This PR will hide personal card if the details aren't loaded.
> Hide personal card if the details aren't loaded.

- Atarashii/res/layout-w720dp/fragment_profile_mal.xml
- Atarashii/res/layout/activity_firstrun.xml
- Atarashii/res/layout/activity_profile.xml
- Atarashii/res/layout/card_detailview_details_mediainfo.xml
- Atarashii/res/layout/friends.xml
- Atarashii/res/layout/record_home_navigationdrawer.xml
- Atarashii/res/values/strings.xml
- Atarashii/res/xml/authenticator.xml
- Atarashii/res/xml/syncadapter.xml
- Atarashii/src/Beta/AndroidManifest.xml
- Atarashii/src/net/somethingdreadful/MAL/Card.java
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
- Atarashii/src/net/somethingdreadful/MAL/FirstTimeInit.java
- Atarashii/src/net/somethingdreadful/MAL/ForumActivity.java
- Atarashii/src/net/somethingdreadful/MAL/ProfileActivity.java
- Atarashii/src/net/somethingdreadful/MAL/Theme.java
- Atarashii/src/net/somethingdreadful/MAL/account/AccountService.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/IGFPagerAdapter.java
- Atarashii/src/net/somethingdreadful/MAL/api/ALInterface.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/ListDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/MessageDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/ShareDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/forum/ForumsPosts.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileFriends.java
- Fix all indents
- add back button to init
- Fix spacing & indents
> Minor beta updates

- Atarashii/build.gradle
- This PR will update all libraries except Crashlytics
> Update all libraries

- Atarashii/build.gradle
- Atarashii/res/values-ar/strings.xml
- Atarashii/res/values-de/strings.xml
- Atarashii/res/values-el/strings.xml
- Atarashii/res/values-es/strings.xml
- Atarashii/res/values-fr/strings.xml
- Atarashii/res/values-nl/strings.xml
- Atarashii/res/values-pl/strings.xml
- Atarashii/res/values-pt-rBR/strings.xml
- Atarashii/res/values-pt-rPT/strings.xml
- Atarashii/res/values-ru/strings.xml
- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/IGFPagerAdapter.java
- Fix the crashlytics crash
- Update Languages
- Add russian & spanish back
- Update libraries
> Fix crashlytics bug & update libraries/languages

- Atarashii/res/values-ar/strings.xml
- Atarashii/res/values-de/strings.xml
- Atarashii/res/values-el/strings.xml
- Atarashii/res/values-es/strings.xml
- Atarashii/res/values-fr/strings.xml
- Atarashii/res/values-nl/strings.xml
- Atarashii/res/values-pl/strings.xml
- Atarashii/res/values-pt-rBR/strings.xml
- Atarashii/res/values-pt-rPT/strings.xml
- Atarashii/res/values-ru/strings.xml
- Atarashii/res/values/strings.xml
- Apply the new translations
- add russian & spanish
- remove turkish from the new updates
> Language updates

- Atarashii/res/values-ar/strings.xml
- Atarashii/res/values-de/strings.xml
- Atarashii/res/values-el/strings.xml
- Atarashii/res/values-es/strings.xml
- Atarashii/res/values-fr/strings.xml
- Atarashii/res/values-nl/strings.xml
- Atarashii/res/values-pl/strings.xml
- Atarashii/res/values-pt-rBR/strings.xml
- Atarashii/res/values-pt-rPT/strings.xml
- Atarashii/res/values-ru/strings.xml
Remove Turkish from the new translations
> Remove Turkish from the new translations

- Atarashii/src/net/somethingdreadful/MAL/ForumActivity.java
Show Snackbar send message also when the comment has been created or updated (Forum)
> Show Snackbar send message also when the comment has been send (Forum)

- Atarashii/src/net/somethingdreadful/MAL/ForumActivity.java
Fix Snackbar message was not shown after a comment update
> Fix Snackbar message was not shown after a comment update

- Atarashii/src/net/somethingdreadful/MAL/account/AccountService.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeList.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/MangaList.java
- Fixes the wrong error message when a record coulnd't be found.
- Fixes the expiretime when something went wrong after a sync.
> Fixes for AniList

- Atarashii/res/layout/dialog_episode_picker.xml
- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
- Atarashii/src/net/somethingdreadful/MAL/PrefManager.java
- Atarashii/src/net/somethingdreadful/MAL/account/AccountService.java
- Atarashii/src/net/somethingdreadful/MAL/api/ALInterface.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALInterface.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/ListDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/NumberPickerDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/sql/MALSqlHelper.java
We do support now 10.0 10 5 100 scores for AniList
Fix crash caused by the accountService
> Fixes account crash & decimal scores

- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/DetailViewDetails.java
- Atarashii/src/net/somethingdreadful/MAL/MALManager.java
- Atarashii/src/net/somethingdreadful/MAL/Theme.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/forum/ForumsPosts.java
- Atarashii/src/net/somethingdreadful/MAL/forum/ForumsTopics.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/NetworkTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/WriteDetailTask.java
> Fix all AniList bugs

- Atarashii/src/net/somethingdreadful/MAL/DetailViewPersonal.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/DatePickerDialogFragment.java
> Fix Date Picker Not Reflecting Existing Date

- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/NumberPickerDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
Fix numberpicker, score, manga corruption.
> Fix numberpicker, score, manga corruption

- Atarashii/src/net/somethingdreadful/MAL/ProfileActivity.java
- Atarashii/src/net/somethingdreadful/MAL/forum/ForumsMain.java
- Atarashii/src/net/somethingdreadful/MAL/forum/ForumsPosts.java
- Atarashii/src/net/somethingdreadful/MAL/forum/ForumsTopics.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileDetailsMAL.java
- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
Fix fast back crashes & cleanup DatabaseManager
> Fix fast back crashes & cleanup DatabaseManager

- Atarashii/src/net/somethingdreadful/MAL/MALManager.java
> Cleanup MALManager

- Atarashii/src/net/somethingdreadful/MAL/dialog/NumberPickerDialogFragment.java
Fix score number input (DetailView)
> Fix score number input (DetailView)

- Atarashii/src/net/somethingdreadful/MAL/Theme.java
Fix crash if score is an empty string (DetailView)
> Fix crash if score is an empty string (DetailView)

- Atarashii/res/layout-w720dp/activity_detailview_details.xml
The titles cards was hovering on the details card.
> Fix title card which was hovering on the stats (MAL & DetailView)

- Atarashii/build.gradle
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/account/AccountService.java
Update Snackbar & Fix menu bug & create Account versions
> Update Snackbar & Fix menu bug & create Account versions

- Atarashii/src/net/somethingdreadful/MAL/FirstTimeInit.java
Fix AniList keeps logged in after a log out
> Fix AniList keeps logged in after a log out

- Atarashii/src/net/somethingdreadful/MAL/IGF.java
Fix Manga View Sometimes Shows Anime.
> Fix Manga View Sometimes Shows Anime.

- Atarashii/src/net/somethingdreadful/MAL/forum/HtmlUtil.java
Fix spoilers & support youtube BBCode
> Fix forums

- Atarashii/res/layout/card_detailview_personal_basic.xml
- Atarashii/src/net/somethingdreadful/MAL/Card.java
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
Fix white border & tags and comments overflow & nullpointer crash type
> Fix white border & tags and comments overflow & nullpointer crash type

- Atarashii/res/values-ar/strings.xml
- Atarashii/res/values-de/strings.xml
- Atarashii/res/values-el/strings.xml
- Atarashii/res/values-es/strings.xml
- Atarashii/res/values-fr/strings.xml
- Atarashii/res/values-nl/strings.xml
- Atarashii/res/values-pl/strings.xml
- Atarashii/res/values-pt-rBR/strings.xml
- Atarashii/res/values-pt-rPT/strings.xml
- Atarashii/res/values-ru/strings.xml
- Atarashii/res/values/strings.xml
Add Turkish in the translations
> Add Turkish in the translations

- Atarashii/build.gradle
- Atarashii/res/values-ar/strings.xml
- Atarashii/res/values-de/strings.xml
- Atarashii/res/values-el/strings.xml
- Atarashii/res/values-es/strings.xml
- Atarashii/res/values-fr/strings.xml
- Atarashii/res/values-ja/strings.xml
- Atarashii/res/values-lv-rLV/strings.xml
- Atarashii/res/values-nl/strings.xml
- Atarashii/res/values-pl/strings.xml
- Atarashii/res/values-pt-rBR/strings.xml
- Atarashii/res/values-pt-rPT/strings.xml
- Atarashii/res/values-ru/strings.xml
- Atarashii/res/values-tr/strings.xml
> Update for RC 1 version 2.1

- Atarashii/build.gradle
- Atarashii/res/values-el/strings.xml
- Atarashii/res/values-pt-rPT/strings.xml
- Atarashii/res/values-ru/strings.xml
- Atarashii/res/values-tr/strings.xml
- build.gradle
> Rc 2 updates

- Atarashii/build.gradle
- Atarashii/src/net/somethingdreadful/MAL/FirstTimeInit.java
- Atarashii/src/net/somethingdreadful/MAL/PrefManager.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/NumberPickerDialogFragment.java
Upgrade version to 2.1 RC 3 & fix rating AL
> Upgrade version to 2.1 RC 3 & fix rating AL

- Atarashii/res/layout/fragment_profile_history.xml
- Atarashii/res/raw/forum_post_structure.html
- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/MALManager.java
- Atarashii/src/net/somethingdreadful/MAL/ProfileActivity.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/ProfilePagerAdapter.java
- Atarashii/src/net/somethingdreadful/MAL/api/ALApi.java
- Atarashii/src/net/somethingdreadful/MAL/api/ALInterface.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALApi.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALInterface.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/Series.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/UserProfile/History.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/UserProfile/User.java
- Atarashii/src/net/somethingdreadful/MAL/forum/HtmlUtil.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileHistory.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileHistoryInterface.java
- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/UserNetworkTask.java
Add history items to the profile
> Add history/activity (profile) support

- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/BackupActivity.java
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/detailView/DetailViewDetails.java
- Atarashii/src/net/somethingdreadful/MAL/detailView/DetailViewGeneral.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/StatusPickerDialogFragment.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileDetailsAL.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/WriteDetailTask.java
Butterknife was crashing due a call which was not set.
The backup had no account type check which caused crashes
> Fix butterknife crash & account type check

- Atarashii/AndroidManifest.xml
- Atarashii/res/layout/widget1.xml
- Atarashii/res/values/strings.xml
- Atarashii/res/xml/widget1_provider.xml
- Atarashii/src/net/somethingdreadful/MAL/DateTools.java
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- Atarashii/src/net/somethingdreadful/MAL/SearchActivity.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/IGFPagerAdapter.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/UserProfile/History.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/RecordPickerDialog.java
- Atarashii/src/net/somethingdreadful/MAL/sql/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/sql/MALSqlHelper.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/NetworkTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/UserNetworkTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/WriteDetailTask.java
- Atarashii/src/net/somethingdreadful/MAL/widgets/Widget1.java
> Add widget support

- Atarashii/build.gradle
- Atarashii/res/layout/theme_viewpager.xml
- Atarashii/src/net/somethingdreadful/MAL/Theme.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/DetailViewPagerAdapter.java
Replace Snackbar & materialtabstrip with the support design library
> Replace Snackbar & materialtabstrip with the support design library

- Atarashii/res/values/strings.xml
- Atarashii/res/xml/settings.xml
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- Atarashii/src/net/somethingdreadful/MAL/PrefManager.java
- Atarashii/src/net/somethingdreadful/MAL/SettingsFragment.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/NumberPickerDialogFragment.java
Fixes #418 Add column number changer to the settings on request of a playstore review.
> Add column number changer to the settings (IGF)

- Atarashii/src/net/somethingdreadful/MAL/Theme.java
> Fix AniList decimal scores which would change to 0 or crash

- Atarashii/res/values/strings.xml
- Atarashii/res/xml/settings.xml
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- Atarashii/src/net/somethingdreadful/MAL/PrefManager.java
- Atarashii/src/net/somethingdreadful/MAL/SettingsFragment.java
- Atarashii/src/net/somethingdreadful/MAL/Theme.java
Add reset preference button & support landschape column (Settings)
> Add reset preference button & support landschape column (Settings)

- Atarashii/res/values/strings.xml
- Atarashii/res/xml/settings.xml
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/PrefManager.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/Manga.java
> Add setting to change the list after adding an anime/ a manga

- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/Manga.java
> Changing from planned to watching update progress to 1

- Atarashii/res/menu/activity_detail_view.xml
- Atarashii/res/values/strings.xml
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/ForumActivity.java
> Add view discussions in the menu (DetailView)

- Atarashii/res/values/strings.xml
- Atarashii/res/xml/settings.xml
- Atarashii/src/net/somethingdreadful/MAL/PrefManager.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/response/AnimeManga/Manga.java
> Update dates automatic when starting/ending an anime or a manga

- Atarashii/res/layout/activity_detailview_personal.xml
- Atarashii/src/net/somethingdreadful/MAL/adapters/DetailViewPagerAdapter.java
Fix crash on some devices due hacky viewpager method
> Fix crash on some devices due hacky viewpager method

- Atarashii/AndroidManifest.xml
- Atarashii/res/values/strings.xml
- Atarashii/res/xml/settings.xml
- Atarashii/src/net/somethingdreadful/MAL/BackupActivity.java
- Atarashii/src/net/somethingdreadful/MAL/MALManager.java
- Atarashii/src/net/somethingdreadful/MAL/PrefManager.java
- Atarashii/src/net/somethingdreadful/MAL/SettingsFragment.java
- Atarashii/src/net/somethingdreadful/MAL/broadcasts/AutoSync.java
- Atarashii/src/net/somethingdreadful/MAL/broadcasts/BackupSync.java
- Atarashii/src/net/somethingdreadful/MAL/forum/ForumsTopics.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/BackupTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/RestoreTask.java
> Enchance backup system

- Atarashii/src/net/somethingdreadful/MAL/tasks/NetworkTask.java
Crash fix random sync & offline support records & snackbar mantaince
> Crash fix random sync & offline support records & snackbar mantaince

- Atarashii/build.gradle
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
Fix Log & update design library
> Fix Log & update design library

- Atarashii/src/net/somethingdreadful/MAL/api/MALModels/AnimeManga/Reviews.java
Fix reviews caused by incompatible field names
> Fix reviews caused by incompatible field names

- Atarashii/src/net/somethingdreadful/MAL/api/MALModels/History.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseTest.java
- Atarashii/src/net/somethingdreadful/MAL/forum/HtmlUtil.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileFriends.java
Fix history crash caused by missing values
> Fix history crash caused by missing values

- Atarashii/src/net/somethingdreadful/MAL/api/BaseModels/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALModels/AnimeManga/Anime.java
Fix storage value bug which didn't let the users display info
> Fix storage value bug which didn't let the users display info

- Atarashii/src/net/somethingdreadful/MAL/api/ALModels/AnimeManga/Reviews.java
- Atarashii/src/net/somethingdreadful/MAL/api/ALModels/AnimeManga/UserList.java
- Atarashii/src/net/somethingdreadful/MAL/api/BaseModels/Profile.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
> Fix AniList bugs and crashes

- Atarashii/src/net/somethingdreadful/MAL/api/ALModels/AnimeManga/Anime.java
> Fix random serializable crash (AL)

- Atarashii/res/layout-w720dp/activity_detailview_details.xml
- Atarashii/res/layout-w720dp/activity_detailview_general.xml
- Atarashii/res/layout-w720dp/activity_detailview_personal.xml
- Atarashii/res/layout/activity_detailview_details.xml
- Atarashii/res/layout/activity_detailview_general.xml
- Atarashii/res/layout/activity_detailview_personal.xml
- Atarashii/res/layout/activity_forum_main.xml
- Atarashii/res/layout/fragment_forum_posts.xml
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/IGF.java
- Atarashii/src/net/somethingdreadful/MAL/adapters/DetailViewPagerAdapter.java
- Atarashii/src/net/somethingdreadful/MAL/api/ALModels/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/ALModels/AnimeManga/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/api/BaseModels/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALModels/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALModels/AnimeManga/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/widgets/Widget1.java
Change personal details by default to update faster
> Change personal details by default to update faster

- Atarashii/src/net/somethingdreadful/MAL/AboutActivity.java
Set version name as header text in the about screen
> Set version name as header text in the about screen

- Atarashii/build.gradle
- Atarashii/src/net/somethingdreadful/MAL/Theme.java
> Update Libraries (sdk 23)

- Atarashii/build.gradle
Force older version for support design due some weird tab behaviour
> Force older version for support design due some weird tab behaviour

- Atarashii/build.gradle
- Atarashii/res/layout/theme_viewpager.xml
Fix tabs acting small on big devices
> Fix tabs acting small on big devices

- Atarashii/src/net/somethingdreadful/MAL/Theme.java
- Atarashii/src/net/somethingdreadful/MAL/api/BaseModels/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/BaseModels/AnimeManga/Manga.java
- Atarashii/src/net/somethingdreadful/MAL/api/BaseModels/Backup.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/database/Query.java
Fix widget sql, backup restore sync & snackbar nullpointer exception
> Fix widget sql, backup restore sync & snackbar nullpointer exception

- Atarashii/src/net/somethingdreadful/MAL/account/AccountService.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALApi.java
- Atarashii/src/net/somethingdreadful/MAL/api/MALModels/History.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseTest.java
- Atarashii/src/net/somethingdreadful/MAL/widgets/Widget1.java
Fix upgrade from old versions & wrong username in history
> Fix upgrade from old versions & wrong username in history

- Atarashii/src/net/somethingdreadful/MAL/api/ALApi.java
- Atarashii/src/net/somethingdreadful/MAL/api/ALModels/History.java
- Atarashii/src/net/somethingdreadful/MAL/api/BaseModels/Profile.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/forum/HtmlUtil.java
Fix AniList profile crashes
Fixes #466
> Fix AniList profile crashes

- Atarashii/src/net/somethingdreadful/MAL/MALManager.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
Fix database not updating records (AniList)
> Fix database not updating records (AniList)

- Atarashii/src/net/somethingdreadful/MAL/api/MALModels/AnimeManga/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseTest.java
- Atarashii/src/net/somethingdreadful/MAL/database/Query.java
- Atarashii/src/net/somethingdreadful/MAL/database/Table.java
Add alternative title support for AL & MAL
> Add alternative title support for AL & MAL

- Atarashii/src/net/somethingdreadful/MAL/api/BaseModels/AnimeManga/Anime.java
- Atarashii/src/net/somethingdreadful/MAL/api/BaseModels/AnimeManga/GenericRecord.java
- Atarashii/src/net/somethingdreadful/MAL/database/Query.java
- Atarashii/src/net/somethingdreadful/MAL/database/Table.java
> Fix database problems

- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/MALManager.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseTest.java
- Atarashii/src/net/somethingdreadful/MAL/dialog/RecordPickerDialog.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/BackupTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/ForumNetworkTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/FriendsNetworkTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/NetworkTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/RestoreTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/UserNetworkTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/WriteDetailTask.java
- Atarashii/src/net/somethingdreadful/MAL/widgets/Widget1.java
Force one instance just like in the past to fix the DB locked issue
> Force one instance just like in the past to fix the DB locked issue

- Atarashii/build.gradle
- Atarashii/libs/mobihelp_sdk_android_v1.5.4/build.gradle
- Atarashii/src/net/somethingdreadful/MAL/MALManager.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/FriendsNetworkTask.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Fix wrong friendlist & add support android 2.0
> Fix wrong friendlist & add support android 2.0

- Atarashii/src/net/somethingdreadful/MAL/DateTools.java
- Atarashii/src/net/somethingdreadful/MAL/ProfileActivity.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileFriends.java
- Atarashii/src/net/somethingdreadful/MAL/profile/ProfileHistory.java
Fix race condition crash on profiles & minor fixes
> Fix race condition crash on profiles & minor fixes

- Atarashii/src/net/somethingdreadful/MAL/AboutActivity.java
- Atarashii/src/net/somethingdreadful/MAL/BackupActivity.java
- Atarashii/src/net/somethingdreadful/MAL/DetailView.java
- Atarashii/src/net/somethingdreadful/MAL/FirstTimeInit.java
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/ProfileActivity.java
- Atarashii/src/net/somethingdreadful/MAL/SearchActivity.java
- Atarashii/src/net/somethingdreadful/MAL/Settings.java
- Atarashii/src/net/somethingdreadful/MAL/Theme.java
This reverts commit 70f26c3ac0af3080fb2d63d358962541453ebfdf.
There were many issues after orientation and backgound loading
> Revert "Change helper intit in Theme to check each time the context"

- Atarashii/res/layout/record_igf_gridview.xml
- Atarashii/res/layout/record_igf_listview.xml
- Atarashii/src/net/somethingdreadful/MAL/Home.java
- Atarashii/src/net/somethingdreadful/MAL/Theme.java
- Atarashii/src/net/somethingdreadful/MAL/api/ALModels/AnimeManga/UserList.java
- Atarashii/src/net/somethingdreadful/MAL/database/DatabaseManager.java
- Atarashii/src/net/somethingdreadful/MAL/database/Query.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/NetworkTask.java
- Atarashii/src/net/somethingdreadful/MAL/tasks/WriteDetailTask.java
- build.gradle
Fix language crash on startup
Fix anilist details overwrite
Fix anilist offline mode crash
Fix offline records not updating
Fix records (offline) not writing to database
Fix crash when the app started fast
Remove transparant drawable which made the grid slower
> Fixes for 2.2.3

- Atarashii/build.gradle
> Update version for 2.2.3
